name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: false      # <<< FIX for exit 143
          timeout: 300s           # optional but recommended
          command_timeout: 300s
          script: |
            PROJECT_DIR="/home/${{ secrets.SERVER_USER }}/dibash-ranjan-cicd"
            REPO_URL="https://github.com/AnantaKumarShrestha/dibash-ranjan-cicd-.git"

            # Go home
            cd /home/${{ secrets.SERVER_USER }}

            # Clone or update
            if [ -d "$PROJECT_DIR" ]; then
              echo "Updating existing project..."
              cd $PROJECT_DIR
              git pull origin main
            else
              echo "Cloning new project..."
              git clone $REPO_URL $PROJECT_DIR
              cd $PROJECT_DIR
            fi

            # Build project
            ./gradlew clean build 

            # Stop any running JAR
            pkill -f ".jar" || true

            # Start new JAR in background
            nohup java -jar build/libs/*.jar > app.log 2>&1 &
            
