name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            PROJECT_DIR="/home/${{ secrets.SERVER_USER }}/dibash-ranjan-cicd"
            REPO_URL="https://github.com/AnantaKumarShrestha/dibash-ranjan-cicd-.git"

            # Go home
            cd /home/${{ secrets.SERVER_USER }}

            # Clone or update
            if [ -d "$PROJECT_DIR" ]; then
              echo "Updating existing project..."
              cd $PROJECT_DIR
              git pull origin main
            else
              echo "Cloning new project..."
              git clone $REPO_URL $PROJECT_DIR
              cd $PROJECT_DIR
            fi

            # Build project
            ./gradlew clean build

            # Run in background with nohup, redirecting output
             java -jar build/libs/*.jar